name: wonders
description: A Flutter project for study.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^5.1.1
  intl: ^0.17.0
  flutter_native_splash: ^2.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/marketing/app-icon-1024.png"

flutter:
  uses-material-design: true

  # 国际化
  # https://docs.flutter.dev/development/accessibility-and-localization/internationalization
  generate: true

  assets:
    - assets/images/_common/
    - assets/images/_common/icons/
    - assets/images/_common/texture/
    - assets/images/chichen_itza/
    - assets/images/christ_the_redeemer/
    - assets/images/colosseum/
    - assets/images/great_wall_of_china/
    - assets/images/machu_picchu/
    - assets/images/petra/
    - assets/images/pyramids/
    - assets/images/taj_mahal/
    - assets/images/collectibles/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Black.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
    - family: Yeseva
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Tenor
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
    - family: B612Mono
      fonts:
        - asset: assets/fonts/B612Mono-Regular.ttf
